Move pipelines to new concourse
- Update vendored concourse code which requires quite a few changes
- Update pipeline names to only include lowercase chars
- Update from go dep to go mod

diff --git a/bin/sync-pipelines b/bin/sync-pipelines
--- a/bin/sync-pipelines
+++ b/bin/sync-pipelines
@@ -2,14 +2,11 @@
 
 set -eu
 
-sanity_pipeline=bosh-io-team-check
-releases_index=../releases/index.yml
+worker_dir="$( cd "$( dirname "$0" )" && cd .. && pwd )"
+releases_index="${worker_dir}/../releases/index.yml"
 
-
-echo "Verifying bosh-io team..."
-echo "If this fails run: fly -t bosh-io login -c https://main.bosh-ci.cf-app.com -n bosh-io"
-fly -t bosh-io pipelines | grep $sanity_pipeline
-
+echo "If this fails run: fly -t bosh-io login -c https://ci.bosh-ecosystem.cf-app.com -n team-bosh-io"
+fly -t bosh-io status
 
 echo
 echo "Pulling latest releases/index.yml..."
@@ -27,24 +24,19 @@ fi
 echo
 echo "Synchronizing pipelines..."
 
-while read org; do
-  echo "$org..."
+pushd ./src/worker >/dev/null
+  while read org; do
+    lowerOrg=$(echo "${org}" | tr '[:upper:]' '[:lower:]')
+    echo "$org..."
 
-  fly -t bosh-io set-pipeline -n \
-    -p "releases:$org" \
-    -c <( go run ./src/worker/main/generatepipeline/main.go "$releases_index" "$org" ) \
-    -l <( lpass show bosh-io-pipelines-reconfigure-secrets --notes )
-
-done < <( set -eu
-  ( set -eu
-
-    # existing orgs
-    fly -t bosh-io pipelines | grep releases | awk '{ print $1 }' | cut -c10- ;
-    # expected orgs
-    go run ./src/worker/main/indexorgs/main.go "$releases_index"
-  ) | sort | uniq
-)
-
+    fly -t bosh-io set-pipeline -n \
+      -p "releases-${lowerOrg}" \
+      -c <( go run main/generatepipeline/main.go "$releases_index" "$org" ) \
+      -l <( lpass show bosh-io-pipelines-reconfigure-secrets --notes )
+  done < <( set -eu
+    go run main/indexorgs/main.go "$releases_index"
+  )
+popd >/dev/null
 
 echo
 echo "Done"
